import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Terminal, Cpu, FileCode, Database, Zap, Plus, Search, ChevronRight } from 'lucide-react';
import { ForgeFile, HeliusAsset } from '../types';

const ForgeTerminal: React.FC = () => {
  const [files, setFiles] = useState<ForgeFile[]>([]);
  const [assets, setAssets] = useState<HeliusAsset[]>([]);
  const [selectedFile, setSelectedFile] = useState<ForgeFile | null>(null);
  const [logs, setLogs] = useState<string[]>([]);
  const [isForging, setIsForging] = useState(false);
  const [activeTab, setActiveTab] = useState<'FILES' | 'ASSETS'>('FILES');
  
  const logEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetchFiles();
    fetchAssets();
    addLog("Forge Interface Initialized...");
    addLog("Connecting to Helius DAS API...");
  }, []);

  useEffect(() => {
    logEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [logs]);

  const addLog = (msg: string) => {
    setLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`]);
  };

  const fetchFiles = async () => {
    try {
      const res = await fetch('/api/forge/files');
      const data = await res.json();
      setFiles(data);
    } catch (err) {
      addLog("Error fetching forge files.");
    }
  };

  const fetchAssets = async () => {
    try {
      const res = await fetch('/api/solana/assets');
      const data = await res.json();
      setAssets(data.items || []);
      addLog(`Synchronized ${data.total || 0} assets from Solana Mainnet.`);
    } catch (err) {
      addLog("Error fetching Solana assets.");
    }
  };

  const initiateForge = async () => {
    setIsForging(true);
    addLog("Initiating Omega-Prime Forge Sequence...");
    
    const steps = [
      "Allocating Sealevel shards...",
      "Generating ZK-Compression proofs...",
      "Encoding BPF bytecode...",
      "Deploying to virtual mainnet..."
    ];

    for (const step of steps) {
      await new Promise(r => setTimeout(r, 1000));
      addLog(step);
    }

    const fileName = `script_${Math.floor(Math.random() * 1000)}.ts`;
    const content = `// Auto-generated by Omega-Prime\nconsole.log('Pulse: ${new Date().toISOString()}');\n// ZK Proof: ${Math.random().toString(36).substring(7)}`;
    
    try {
      const res = await fetch('/api/forge/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: fileName, content, type: 'script' })
      });
      const newFile = await res.json();
      setFiles(prev => [...prev, newFile]);
      addLog(`Successfully birthed: ${fileName}`);
    } catch (err) {
      addLog("Forge failed: Connection disrupted.");
    } finally {
      setIsForging(false);
    }
  };

  return (
    <div className="h-full flex flex-col p-6 space-y-6 overflow-hidden">
      <div className="flex justify-between items-end border-b border-gray-800 pb-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Cpu className="w-4 h-4 text-nexus-accent animate-pulse" />
            <span className="text-nexus-accent font-mono text-xs tracking-widest uppercase">Omega-Prime // Data-Script Forge</span>
          </div>
          <h2 className="text-3xl font-bold text-white tracking-wider font-mono uppercase">Neural Forge Terminal</h2>
        </div>
        <div className="flex gap-2">
          <button 
            onClick={() => setActiveTab('FILES')}
            className={`px-4 py-1 text-xs font-bold font-mono border transition-all ${activeTab === 'FILES' ? 'bg-nexus-accent text-black border-nexus-accent' : 'text-gray-500 border-gray-800 hover:text-white'}`}
          >
            VIRTUAL_FS
          </button>
          <button 
            onClick={() => setActiveTab('ASSETS')}
            className={`px-4 py-1 text-xs font-bold font-mono border transition-all ${activeTab === 'ASSETS' ? 'bg-nexus-purple text-white border-nexus-purple' : 'text-gray-500 border-gray-800 hover:text-white'}`}
          >
            SOL_ASSETS
          </button>
        </div>
      </div>

      <div className="flex-1 flex gap-6 overflow-hidden">
        {/* Left Panel: Explorer */}
        <div className="w-1/3 flex flex-col gap-4 overflow-hidden">
          <div className="bg-nexus-panel border border-gray-800 rounded-xl flex-1 flex flex-col overflow-hidden">
            <div className="p-3 border-b border-gray-800 flex justify-between items-center bg-black/30">
              <span className="text-xs font-mono text-gray-400 uppercase tracking-widest">
                {activeTab === 'FILES' ? 'FileSystem' : 'Helius Assets'}
              </span>
              {activeTab === 'FILES' && (
                <button 
                  onClick={initiateForge}
                  disabled={isForging}
                  className="p-1 hover:bg-nexus-accent hover:text-black rounded transition-colors text-nexus-accent"
                >
                  <Plus className="w-4 h-4" />
                </button>
              )}
            </div>
            
            <div className="flex-1 overflow-y-auto p-2 space-y-1">
              {activeTab === 'FILES' ? (
                files.map(file => (
                  <div 
                    key={file.id}
                    onClick={() => setSelectedFile(file)}
                    className={`p-2 rounded flex items-center gap-3 cursor-pointer transition-colors ${selectedFile?.id === file.id ? 'bg-nexus-accent/10 border border-nexus-accent/30' : 'hover:bg-white/5'}`}
                  >
                    <FileCode className={`w-4 h-4 ${file.type === 'script' ? 'text-nexus-gold' : 'text-nexus-accent'}`} />
                    <div className="flex-1 overflow-hidden">
                      <div className="text-sm font-mono text-gray-200 truncate">{file.name}</div>
                      <div className="text-[10px] text-gray-500 uppercase">{file.type}</div>
                    </div>
                  </div>
                ))
              ) : (
                assets.map(asset => (
                  <div key={asset.id} className="p-2 rounded flex items-center gap-3 hover:bg-white/5 border border-transparent hover:border-gray-800 transition-all">
                    {asset.content.links?.image ? (
                      <img src={asset.content.links.image} alt="" className="w-8 h-8 rounded bg-gray-900 object-cover" />
                    ) : (
                      <Database className="w-8 h-8 p-1.5 bg-gray-900 text-nexus-purple rounded" />
                    )}
                    <div className="flex-1 overflow-hidden">
                      <div className="text-sm font-mono text-gray-200 truncate">{asset.content.metadata.name || 'Unknown Asset'}</div>
                      <div className="text-[10px] text-gray-500 truncate">{asset.id.slice(0, 12)}...</div>
                    </div>
                    {asset.compression?.compressed && (
                      <Zap className="w-3 h-3 text-nexus-gold animate-pulse" />
                    )}
                  </div>
                ))
              )}
            </div>
          </div>

          {/* Logs */}
          <div className="h-1/3 bg-black border border-gray-800 rounded-xl p-3 font-mono text-[10px] overflow-y-auto flex flex-col">
            <div className="text-gray-600 mb-2 uppercase tracking-widest border-b border-gray-900 pb-1">System Logs</div>
            <div className="flex-1 space-y-1">
              {logs.map((log, i) => (
                <div key={i} className="text-gray-400">
                  <span className="text-nexus-accent mr-2">❯</span>{log}
                </div>
              ))}
              <div ref={logEndRef} />
            </div>
          </div>
        </div>

        {/* Right Panel: Editor/Viewer */}
        <div className="flex-1 bg-nexus-panel border border-gray-800 rounded-xl flex flex-col overflow-hidden relative">
          <div className="absolute inset-0 pointer-events-none opacity-5">
            <div className="w-full h-full bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-nexus-accent via-transparent to-transparent"></div>
          </div>
          
          {selectedFile ? (
            <>
              <div className="p-3 border-b border-gray-800 flex justify-between items-center bg-black/30 z-10">
                <div className="flex items-center gap-2">
                  <FileCode className="w-4 h-4 text-nexus-accent" />
                  <span className="text-xs font-mono text-white">{selectedFile.name}</span>
                </div>
                <span className="text-[10px] text-gray-500 font-mono">{new Date(selectedFile.timestamp).toLocaleString()}</span>
              </div>
              <div className="flex-1 p-6 font-mono text-sm text-gray-300 overflow-y-auto z-10">
                <pre className="whitespace-pre-wrap leading-relaxed">
                  {selectedFile.content}
                </pre>
              </div>
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-gray-600 font-mono">
              <Terminal className="w-16 h-16 mb-4 opacity-10" />
              <p className="tracking-widest uppercase text-xs">Select a matrix from the virtual filesystem</p>
            </div>
          )}

          {isForging && (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="absolute inset-0 bg-black/80 backdrop-blur-sm z-20 flex flex-col items-center justify-center"
            >
              <div className="relative">
                <div className="w-24 h-24 border-2 border-nexus-accent/20 rounded-full animate-ping"></div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <Cpu className="w-10 h-10 text-nexus-accent animate-pulse" />
                </div>
              </div>
              <p className="mt-6 text-nexus-accent font-mono text-sm tracking-[0.3em] animate-pulse">FORGING_DATA_SCRIPT...</p>
            </motion.div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ForgeTerminal;
